#**Exemplos de Programação Funcional e Machine Learning**
**prof: Sergio Assuncao Monteiro, DSc**

*   linkedin: https://www.linkedin.com/in/sergio-assun%C3%A7%C3%A3o-monteiro-b781897b/
*   lattes: http://lattes.cnpq.br/9489191035734025


# **Funções Puras**

In [7]:
def funcao_pura(lista):
	nova_lista = []
	for i in lista:
		nova_lista.append(i**2)
	return nova_lista

In [8]:
lista_original = [1, 2, 3, 4]
lista_modificada = funcao_pura(lista_original)

In [9]:
print(f'Lista original: {lista_original}')
print(f'Lista modificada: {lista_modificada}')

Lista original: [1, 2, 3, 4]
Lista modificada: [1, 4, 9, 16]


# **Programação Funcional**

**Função Lambda**

In [10]:
quadrado = lambda x: x ** 2

In [11]:
numero = 10

In [13]:
print(f'{numero} ao quadrado é: {quadrado(numero)}')

10 ao quadrado é: 100


**Map**

In [14]:
lista_original_v02 = [1, 2, 3, 4]

In [15]:
lista_modificada_v02 = list(map(quadrado, lista_original_v02))

In [16]:
lista_modificada_v02

[1, 4, 9, 16]

**Filter**

In [23]:
idades = [21, 12, 17, 19, 25, 32]

In [24]:
f_maior_que_18 = lambda x : True if (x >= 18) else False

In [25]:
maior_de_idade = list(filter(f_maior_que_18, idades))

In [26]:
maior_de_idade

[21, 19, 25, 32]

**Reduce**

In [27]:
from functools import reduce

In [28]:
adicao = lambda x, y: x + y

In [30]:
lista = [1, 2, 3, 4, 5]

In [32]:
somatorio = reduce(adicao, lista)

In [33]:
print(f'O somatório dos elementos da lista {lista} é: {somatorio}')

O somatório dos elementos da lista [1, 2, 3, 4, 5] é: 15


# **Aprendizado de Máquina**

In [42]:
from sklearn import datasets
import pandas as pd
import numpy as np

In [43]:
iris = datasets.load_iris()

In [44]:
iris.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [45]:
iris = pd.DataFrame(
    data= np.c_[iris['data'], iris['target']],
    columns= iris['feature_names'] + ['target']
    )

In [46]:
iris.head(5)

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0     0.0  
1     0.0  
2     0.0  
3     0.0  
4     0.0

In [47]:
from sklearn.model_selection import train_test_split

In [50]:
X = iris.drop(['target'], axis=1)

# Conversao para um vetor numpy com a associacao das características "petal length" e "petal width"
X = X.to_numpy()[:, (2,3)]
y = iris['target']

In [52]:
# Separação dos dados para treinamento e teste
X_treino, X_teste, y_treino, y_teste = train_test_split(X, y,
                                                        test_size=0.25,
                                                        random_state=76)

In [53]:
from sklearn.linear_model import LogisticRegression

#Regressao Logistica
log_reg = LogisticRegression()
log_reg.fit(X_treino,y_treino)

LogisticRegression()

In [54]:
predicoes = log_reg.predict(X_teste)

In [55]:
predicoes

array([0., 1., 0., 2., 2., 1., 0., 1., 1., 2., 0., 2., 1., 1., 0., 0., 0.,
       2., 1., 0., 2., 0., 0., 0., 0., 0., 2., 1., 0., 1., 2., 2., 1., 2.,
       1., 0., 0., 0.])

In [56]:
from sklearn import metrics

# Confusion matrix
print(metrics.confusion_matrix(y_teste, predicoes))

[[17  0  0]
 [ 0 11  1]
 [ 0  0  9]]
